# Stage 1: Build the app
FROM node:22-alpine as builder
WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

# Stage 2: Serve the build with Nginx
FROM nginx:alpine
# Remove default Nginx configuration if necessary and copy your custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy the production build files from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
